// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 重置滤波器状态
void initAhrs() => RustLib.instance.api.crateApiImuInitAhrs();

/// 接收来自 Dart 的 IMU 数据（加速度计和陀螺仪），进行融合计算
///
/// * `ax, ay, az`: 加速度计 (m/s^2)
/// * `gx, gy, gz`: 陀螺仪 (rad/s)
///
/// 返回: (pitch, roll, yaw) 包含三轴欧拉角的元组 (单位: 弧度)
(double, double, double) updateAhrs({
  required double ax,
  required double ay,
  required double az,
  required double gx,
  required double gy,
  required double gz,
}) => RustLib.instance.api.crateApiImuUpdateAhrs(
  ax: ax,
  ay: ay,
  az: az,
  gx: gx,
  gy: gy,
  gz: gz,
);
